version: '3.7'

services: 
  web:
    build: ./app
    command: gunicorn fotos.wsgi:application --bind 0.0.0.0:8000
    ports: 
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    build: ./postgis
    volumes:
      - postgis_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgis_data: