# Generated by Django 3.1.4 on 2021-01-13 10:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argazki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('orientacion', models.IntegerField()),
                ('fecha', models.DateField()),
                ('archivo', models.CharField(max_length=50)),
            ],
        ),
    ]
